In [12]:
import numpy as np

## first Markdown

In [ ]:
print("hi")

hi


In [10]:
print(3+2)

5


## First array In Numpy

In [14]:
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)

[1 2 3 4]


In [16]:
arr_2d = np.array([
                    [1, 2, 3],
                    [4, 5, 6]
                ])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


## Numpy array VS List
- Time taken to create a list and Numpy operation on Multiplication

In [20]:
py_list = [1 ,2 ,3]
print("Multiply list in Py ",py_list * 2)

import time

start_time = time.time()
py_list = [i * 2 for i in range(10000000)]
print("Time Taken for List", time.time()- start_time)

start_time = time.time()
numpy_list = np.arange(10000000) * 2

print("Time Taken for numpy list", time.time()- start_time)

Multiply list in Py  [1, 2, 3, 1, 2, 3]
Time Taken for List 0.5837750434875488
Time Taken for numpy list 0.022022008895874023
