In [12]:
import numpy as np

## first Markdown

In [ ]:
print("hi")

hi


In [10]:
print(3+2)

5


## First array In Numpy

In [14]:
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)

[1 2 3 4]


In [16]:
arr_2d = np.array([
                    [1, 2, 3],
                    [4, 5, 6]
                ])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


## Numpy array VS List
- Time taken to create a list and Numpy operation on Multiplication

In [21]:
py_list = [1 ,2 ,3]
print("Multiply list in Py ",py_list * 2)

import time

start_time = time.time()
py_list = [i * 2 for i in range(10000000)]
print("Time Taken for List", time.time()- start_time)

start_time = time.time()
numpy_list = np.arange(10000000) * 2

print("Time Taken for numpy list", time.time()- start_time)

Multiply list in Py  [1, 2, 3, 1, 2, 3]
Time Taken for List 0.6947648525238037
Time Taken for numpy list 0.08411097526550293


## Vector, Matrix & tensor

In [25]:
np_vector = np.array([1, 2, 3])
print("Vector: ", np_vector)

np_matrix = np.array([[1, 2, 3],
                      [4, 5, 6]])
print("matrix: ", np_matrix)

np_tensor = np.array([[[1, 3],[2, 3]],
                       [[4, 5],[6, 7]]])
print("Tensor: ", np_tensor)


Vector:  [1 2 3]
matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 3]
  [2 3]]

 [[4 5]
  [6 7]]]


In [29]:
print("SHape: ",np_tensor.shape)
print("Dimention: ",np_tensor.ndim)
print("Size: ",np_tensor.size)
print("Dtype: ",np_tensor.dtype)

SHape:  (2, 2, 2)
Dimention:  3
Size:  8
Dtype:  int64


In [37]:
array_2D = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

print(array_2D[:2,1:])
print(array_2D[1:,1:])

[[2 3]
 [5 6]]
[[5 6]
 [8 9]]
